### ISSUE TITLE
upgrade to node 16

### ISSUE THREAD

**Issue by tobiasnteireho** [CCALI/a2jauthor#277]
node 16 is current active lts. Attempting to upgrade to 16.13.1 yields following error at steal transpilation step

```
Running "steal-build:author" (steal-build) task
OPENING: a2jauthor/app
OPENING: a2jauthor@7.1.0#app-template
OPENING: a2jauthor@7.1.0#legacy/legacy
OPENING: a2jauthor@7.1.0#styles.less!steal-less@1.3.4#less
OPENING: a2jauthor@7.1.0#ckeditor/ckeditor
Transpiling...
Build has failed.  Error: Line 2094: Unexpected token .
    at ErrorHandler.constructError (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parsePrimaryExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2366:38)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2899:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseUpdateExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3004:26)
    at Parser.parseUnaryExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3048:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseExponentiationExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3054:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseBinaryExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3089:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseConditionalExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3141:26) {
  index: 54784,
  lineNumber: 2094,
  description: 'Unexpected token .',
  message: 'Unable to transpile pdfjs-dist@2.12.313#build/pdf: \n' +
    '\n' +
    'Line 2094: Unexpected token .'
}
Warning: Unable to transpile pdfjs-dist@2.12.313#build/pdf: 

Line 2094: Unexpected token . Use --force to continue.

Aborted due to warnings.
```

**Comment by tobiasnteireho** [comment]
same error on node 14

```
Running "steal-build:author" (steal-build) task
OPENING: a2jauthor/app
OPENING: a2jauthor@7.1.0#app-template
OPENING: a2jauthor@7.1.0#legacy/legacy
OPENING: a2jauthor@7.1.0#styles.less!steal-less@1.3.4#less
OPENING: a2jauthor@7.1.0#ckeditor/ckeditor
Transpiling...
Build has failed.  Error: Line 2094: Unexpected token .
    at ErrorHandler.constructError (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.parsePrimaryExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2366:38)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseLeftHandSideExpressionAllowCall (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2899:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseUpdateExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3004:26)
    at Parser.parseUnaryExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3048:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseExponentiationExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3054:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseBinaryExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3089:26)
    at Parser.inheritCoverGrammar (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:2285:37)
    at Parser.parseConditionalExpression (/vol/data/sites/hydra.a2jauthor.org/a2jauthor-node16/node_modules/esprima/dist/esprima.js:3141:26) {
  index: 54784,
  lineNumber: 2094,
  description: 'Unexpected token .',
  message: 'Unable to transpile pdfjs-dist@2.12.313#build/pdf: \n' +
    '\n' +
    'Line 2094: Unexpected token .'
}
Warning: Unable to transpile pdfjs-dist@2.12.313#build/pdf: 

Line 2094: Unexpected token . Use --force to continue.
```

**Comment by tobiasnteireho** [comment]
starting with last known good `package.json` which includes stealjs 1.x, yields

```
Build has failed.  [TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator
  at writeFile (node:fs:2106:5)
  at /vol/data/sites/hydra.a2jauthor.org/a2jauthor-fafo/node_modules/pdenodeify/lib/main.js:18:20
  at new Promise (<anonymous>:null:null)
  at /vol/data/sites/hydra.a2jauthor.org/a2jauthor-fafo/node_modules/pdenodeify/lib/main.js:10:12
  at /vol/data/sites/hydra.a2jauthor.org/a2jauthor-fafo/node_modules/steal-tools/lib/bundle/write_bundles.js:64:13
  at Function.all (<anonymous>:null:null)
] {
  code: 'ERR_INVALID_ARG_TYPE'
}
Warning: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of SourceMapGenerator Use --force to continue.

Aborted due to warnings.
```
This is resolved when setting sourcemaps to false.
